PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wds: <http://www.wikidata.org/entity/statement/>
PREFIX wdv: <http://www.wikidata.org/value/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://wikidata.org/prop/>
PREFIX ps: <http://wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX db: <http://www.semanticweb.org/nfb4/ontologies/2022/1/untitled-ontology-6#>

# NOT FINISHED

SELECT DISTINCT ?label (COUNT(?mu) AS ?muCount) (COUNT(?gal) AS ?galCount)
WHERE 
{
	?c rdf:type db:City ;
  	db:CityWikiRelation ?wikicity
  
  SERVICE <http://query.wikidata.org/sparql> {
    ?wikicity rdfs:label ?label
    FILTER (lang(?label) = "en" )
    ?mu wdt:P31/wdt:P279* wd:Q33506;
    wdt:P276 ?wikicity.
    ?gal wdt:P31 wd:Q1007870;
    wdt:P276 ?wikicity.
  }
}
GROUPBY ?label
